### ISSUE TITLE
Hypothes.is / Annotation example integration

### ISSUE THREAD

**Issue by JakeHartnell** [readium/readium-js#109]
Was talking with @rkwright today at the Hacking the Codex hackathon, and we talked about what would be needed for a Hypothesis integration (many people have asked us for one!).

There are a couple ways we could integrate. The simplest approach could be injecting JavaScript in the iframe, a guest annotator that can communicate with a host in the parent document. This is largely to be able to get selection data and draw highlights. Will we be able to do this with the upcoming work on plugins?

If this will not work there are other possibilities, for example, a highlight and getSelection API. We need to be able to listen for selection events in the iframe and get more selection data than merely the CFI (for example, if there are PDF versions of the same document we would like to be able to migrate annotations between them). We also need to be able to create highlights where annotations exist.

It will be easiest if we can inject our guest script. Thoughts?

**Comment by JCCR** [comment]
I can see this being a plugin, yes. We would need to develop a better facility to inject scripts into the iframes. What we have now (but not in master/develop yet) is this:

`reader.getLoadedContentFrames()`
- returns an array of tuples <Iframe, spineItem>
- This is an array because depending on the page spread, or scroll view we could have multiple iframes  being displayed. Right now to inject JS, it is up to you to include script tags, and so on once you have the iframe reference.

Managing the injection and state from the iframes is probably going to be the biggest challenge.
If the host of the annotator can handle multiple guests then this will be easier.

**Comment by ryanackley** [comment]
We should take care not to expose the iframe to plugins. There is a known security issue caused by Readium's reliance on direct iframe access. I had the impression that we planned on fixing it one day. If we allow plugin developers direct access, it will exacerbate the problem by potentially breaking plugin compatibility if we ever decide to fix it. 

My suggestion would be to expose an opaque API for injecting scripts. Under the hood it could use direct iframe access.

**Comment by JCCR** [comment]
@JakeHartnell 
How does Hypothes.is/Annotator render the highlights? Do you guys do span element wrapping of the text? One of my concerns with highlighting + EPUB docs is to not disrupt the integrity of the original DOM. This is to avoid CFI invalidation. 

With highlighting what we have tries is to not insert spans and instead use range info + absolutely positioned divs to indirectly render highlights. 
In some unavoidable cases (mathjax integration), when we have to do DOM manipulation we mark certain element nodes and their subtrees as "blacklisted" areas. Unfortunately with what we have now this is not ideal for highlights because essentially every time you create a highlight you are removing that area of text away from the CFI resolution.

I personally think using spans and having the ability to modify the DOM without the CFI worry will be the best, both in ease of development and end user experience. But in order to have this we need to spend some development time into something like this:
https://github.com/readium/readium-cfi-js/pull/19

**Comment by JCCR** [comment]
@ryanackley

Yea, the opaque API is a good solution. I want the plugins API to head towards this direction, with what we have now everything is a direct access to the Reader view API. I want to stress this to others that this issue with breaking plugin compatibility on changes applies to more than just the iframe security issue.

**Comment by rkwright** [comment]
I think we have reached a point where a brief telecon would be helpful and more efficient. I'll propose something.

**Comment by coler-j** [comment]
Doesn't this exist now? Should this issue be closed then?

**Comment by danielweck** [comment]
@jccr are you happy closing this? (I certainly am)

**Comment by jccr** [comment]
Yes. Let's close this.
