### ISSUE TITLE
Where can I find the list of Blob url for a book?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#154]
I am trying to implement a pagination system.
I found each chapter has a unique blob url in order to make the iframe render it,  as showing below:

![qq 20161219142716](https://cloud.githubusercontent.com/assets/5040078/21303122/0d1ec352-c5f7-11e6-8e19-5f020f99ccf4.png)

I would like to access all the blob urls so that I can get access to each document, and then I can do some calculation to implementing the pagination system.  It would be great if there is a list of spineItems with such blob url. Where can I get these information? 

Thanks.

**Comment by danielweck** [comment]
1) a BlobURI is generated by Readium to "feed" the pre-fetched contents of HTML documents into `iframe@src` *only* in the case of the cloud reader (i.e. not the Chrome app, not the native apps).
See: https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js#L100
```javascript
var documentDataUri = window.URL.createObjectURL(
    new Blob([contentDocumentData], {'type': contentType})
);
```

2) ...in fact, the BlobURI technique is *not* used for Internet Explorer, Edge, and in some other edge cases (some hybrid apps, or some mobile browsers), because of technical limitations on those particular target platforms. Instead, `document.write()` is used.
See https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js#L112
```javascript
iframe.contentWindow.document.open();

                if (window.MSApp && window.MSApp.execUnsafeLocalFunction) {
                    window.MSApp.execUnsafeLocalFunction(function() {
                        iframe.contentWindow.document.write(contentDocumentData);
                    });
                } else {
                    iframe.contentWindow.document.write(contentDocumentData);
                }
```

3) Note that *only* the HTML documents are loaded as binary blobs (i.e. not the associated CSS, images, etc.) *unless* there are obfuscated fonts, or the EPUB is zipped / packed, in which case *all* the resources are prefetched and stored in BlobURIs.
See https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js#L69
```javascript
 var shouldConstructDomProgrammatically = getCurrentResourceFetcher().shouldConstructDomProgrammatically();
```

4) *only* the current visible spine item HTML documents are dynamically loaded, not the other ones that are in the EPUB spine. In other words, your pagination system would need to statically preload / prefetch the entire ebook in order to compute / predict the number of pages. Another method would be to estimate paginated units by considering an average of number of characters, etc. Note that some time ago an attempt was made to prefetch the nearest spine item neighbours of the current opened documents, but this was primarily to address performance issues during "page turning". See the feature branch: https://github.com/readium/readium-shared-js/tree/feature/prefetch

**Comment by hz0324** [comment]
@danielweck 
Thank you very much, sir.
Could you please tell me how to preload / prefetch the entire epub book? 

I have read a few posts here and found you guys having a related discussion about 1 year ago. Someone suggested iterating each spineItem and then do the calculation to get pagination info. But I haven't find a way to get access to all the spineItems / documents. 

As long as I can get access to all the spineItem in DOM format, I will figure out how to write a pagination system.

Thanks in advance.

**Comment by danielweck** [comment]
`reader.spine().items[i].href`

https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L350
```javascript
    /**
     * Returns a representation of the spine as a data object, also acts as list of spine items
     *
     * @returns {Models.Spine}
     */
    this.spine = function () {
        return _spine;
    };
```


https://github.com/readium/readium-shared-js/blob/develop/js/models/spine.js#L39
```javascript
    /**
     * The collection of spine items
     *
     * @property items
     * @type Array
     */
    this.items = [];
```


https://github.com/readium/readium-shared-js/blob/develop/js/models/spine_item.js#L52
```javascript
    /**
     * The href of the spine item, i.e. the URI to the resource in the EPUB
     * which the spineitem will render
     *
     * @property href
     * @type String
     * @default  None
     */
    this.href = itemData.href;
```

**Comment by hz0324** [comment]
Thank you, helps a lot!
