### ISSUE TITLE
Is there a way to access cover image as blob?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#156]
We want to get the cover image of opened book for certain usage.
Is there a easy way in readium-js to achieve this goal?

Thanks

PS: I tried to search this repo using keyword "cover image", and this code snippet showed up, I wondered whether I can access the var cover in it.
![qq 20161220211710](https://cloud.githubusercontent.com/assets/5040078/21351851/c3301bca-c6f9-11e6-9e71-9307aaa4eb23.png)

**Comment by danielweck** [comment]
Option 1) if you know the URL to `package.opf` (or whatever the file name of the EPUB's OPF XML file is), then you can use `PackageParser.getCoverHref()` which returns a relative path based on the OPF's URL (then you can invoke XmlHttpRequest to read the image binary Blob, if you need to):
https://github.com/readium/readium-js-viewer/blob/develop/src/js/PackageParser.js

**Comment by danielweck** [comment]
Option 2) modify your `openPackageDocument()` function to compute the cover image absolute URL in the ` function(packageDocument, options){}` callback:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L156

Note that `packageDocument.getMetadata().cover_href` is identical to `options.metadata.cover_href`:

```javascript
  readium.openPackageDocument(
            
            ebookURL,
            
            function(packageDocument, options){
// SAME VALUES:
console.debug(packageDocument.getMetadata().cover_href);
console.debug(options.metadata.cover_href);
...
```

**Comment by danielweck** [comment]
To resolve the absolute URL in option 2, use `readium.getCurrentPublicationFetcher().convertPathRelativeToPackageToRelativeToBase(COVER_PATH)`:

```javascript
  readium.openPackageDocument(
            
            ebookURL,
            
            function(packageDocument, options){
var url = ebookURL + "/" + readium.getCurrentPublicationFetcher().convertPathRelativeToPackageToRelativeToBase(options.metadata.cover_href);

Dialogs.showModalMessageEx("EPUB cover image", $('<p>'+url+'</p><img src="'+url+'" style="height:100%; width:100%" />'));

...
```

**Comment by danielweck** [comment]
Concrete example usage in the Readium cloud reader:
https://github.com/readium/readium-js-viewer/commit/fd06e09146274c0b2aa17a574edc0f26c5cfea06
("share bookmark" feature)

**Comment by hz0324** [comment]
Thank you very much, sir.
Your response helps us find a way to work on.

But unfortunately, I can not make the code you provided work in our app. I guess it has something to do with the unique way we design our app.

In our app, when user drops an epub book, we get it as a File object and save the book to the indexedDB as Blob, then we call the readiumJS to open the Blob that fetched from indexedDB. So, in our version of openPackageDocument(), the ebookURL parameter is accutually a File/Blob object from indexedDB, not a real URL path from server or remote path. As showing below:

![qq 20161221202509](https://cloud.githubusercontent.com/assets/5040078/21389325/149b0ff2-c7bc-11e6-9fe9-18e5c3a454cc.png)

In our case, `using getCurrentPublicationFetcher().getEbookURL_FilePath() + "/" + coverPath` dosen't give use a working url. It is something like bookname.epub/cover.jpg, which is not working fro img element.

I am still truggling to solve this, but since our code is different from the standard Readium Cloud Reader, I think I need to find another way to solve the problem. Due to the same reason, I don't think option 1 will work in our app.

Thank you anyway. 
Your answer is really thought-provoking.

**Comment by danielweck** [comment]
Ah yes. In fact you can also reproduce this problem by drag-and-drop an EPUB file onto the official cloud reader app, in a web browser:
https://readium.firebaseapp.com
...then click the button "share reader bookmark" in the toolbar at the top (icon looks like a chain link), and see how the cover image is missing. That is indeed because there is no string URL for the absolute location of the ebook, but instead a BlobURI (or a File object, with a simple filename).

Another way to reproduce this problem is to open (again, with the cloud reader app) an exploded / unzipped EPUB that contains obfuscated fonts (because in this case the whole EPUB ; every single resource ; must be prefetched, parsed and loaded as binary Blobs).

So yes, maybe you can fetch the cover image Blob from a cache?

**Comment by hz0324** [comment]
Thanks. 

Fetching the cover image Blob from cache is another approach I am going to try. 
But I have found a new problem. Some books have a cover image, but it dosen't show up in the book spines, maybe the creator think it is not neccessary to put it in the reading list. This will compremise both fetching from img element approach and fetching from cache approach. 

I am gonna try unzip the File in browser-side js and get the image directly. Wish me luck. ^_^

**Comment by danielweck** [comment]
The official Readium cloud reader already supports unzipping EPUB on the client side, either from full EPUB Blob (which is what happens when drag+drop ebook file on web browser), or via HTTP 1.1 partial requests / byte range (which is what happens when an ebook file is hosted online) to avoid downloading the whole package at once, and to avoid loading it entirely in memory.
We strongly recommend exploding / unzipping EPUBs on the server side, because of how web browsers work.
In a not-too-distant future, Service Workers will help address this limitation, in fact there is already a proof of concept in the `feature/ServiceWorker` branch (we intercept HTTP / XmlHttpRequest / Fetch events, and we dynamically convert the unzipped Blobs to HTTP response payloads):
https://github.com/readium/readium-js-viewer/tree/feature/ServiceWorker
https://github.com/readium/readium-js/tree/feature/ServiceWorker

**Comment by hz0324** [comment]
Great, glad to hear that. We do plan to unzip EPUBs on the server side in the future. 
But right now, our app only have a off-line version, we can not rely on server-side code to solve this very problem.

As to "The official Readium cloud reader already supports unzipping EPUB on the client side", is there a way to get access to each file inside the EPUB blob after it was upzipped? I am planning to try jszip.js tomorrow, if there is an official way to access the image file, it would be great.

**Comment by danielweck** [comment]
I implemented the Blob retrieval using existing Readium functions. I will show you.

**Comment by danielweck** [comment]
```javascript
                    var fetcher = readium.getCurrentPublicationFetcher();

                    var coverHref = currentPackageDocument.getMetadata().cover_href;
                    if (coverHref) {
                        var coverPath = fetcher.convertPathRelativeToPackageToRelativeToBase(coverHref);
                        var relPath = "/" + coverPath;

                        if (fetcher.shouldConstructDomProgrammatically()) {

                            fetcher.relativeToPackageFetchFileContents(relPath, 'blob', function (res) {
                                if(res) {
                                    try {
                                        var blobURI = window.URL.createObjectURL(res);
...
                                    } catch (err) {
                                        // ignore
                                        console.error(err);
                                    }
                                }
                            }, function (err) {
                                // ignore
                                console.error(err);
                            });
                        } else {
                            var ebookCoverImageURL = fetcher.getEbookURL_FilePath() + relPath;
...
                        }
                    }
```
See: https://github.com/readium/readium-js-viewer/commit/adb56ca28a62c0ce58d5e3e81ecf35e8518eb0a4

**Comment by hz0324** [comment]
Thank you sir, you are being really helpful.
The code snippet you provided right above is working perfectly! 

I appreciate it very much.
^_^

**Comment by danielweck** [comment]
The resource fetcher should work with content that is not already loaded in the BlobURI cache for the current spine item / HTML document. So yes, in principle this technique can be used to index / prefetch an entire publication.
