### ISSUE TITLE
Is there a way to detect whether a epub file is encrypted?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#164]
Some users are trying to drop encrypted book to our app. Readium-js console.log the error.
We want to warn user do not use encrypted book, how to do it?

Is there a way to detect whether a epub file is encrypted ?

Thanks

**Comment by rkwright** [comment]
You could look in the encryption.xml where the type of encryption is required to be listed.   But you need to ignore the obfuscation "encryption" setting, i.e. Readium will automatically decrypt obfuscated fonts.  But if you find other encryption info you could conclude that at least part of the book is encrypted.

For example, here is the encryption info for the two types of obfuscation (Adobe's original, and the revised method adoption in EPUB 2.x)

      <EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#">
         <EncryptionMethod Algorithm="http://ns.adobe.com/pdf/enc#RC"/>
         <CipherData>
            <CipherReference URI="fonts/sandome.adb.ttf"/>
        </CipherData>
    </EncryptedData>
    <EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#">
        <EncryptionMethod Algorithm="http://www.idpf.org/2008/embedding"/>
        <CipherData>
            <CipherReference URI="fonts/sandome.obf.ttf"/>
        </CipherData>
    </EncryptedData>

Note that there will be an <EncryptedData> entry for each encrypted resource, so there could be a lot of entries.  Offhand, I don't know an easier method.
@danielweck  Comment?

**Comment by danielweck** [comment]
You probably need to add this functionality, but there are existing build blocks:

`PublicationFetcher` has an internal / private `_encryptionHandler` member:
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/publication_fetcher.js#L31

...and the `EncryptionHandler.isEncryptionSpecified()` function returns true when the `encryption.xml` maps at least one resource with an algorithm.
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/encryption_handler.js#L88
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/encryption_handler.js#L159

In which case, in order to determine whether there are encrypted resources other than obfuscated fonts, you could iterate through manifest items and use `getEncryptionMethodForRelativePath()` to check for `undefined` return value:
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/encryption_handler.js#L93

...which indicates that a resource is encrypted with algorithms other than IDPF / Adobe:
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/encryption_handler.js#L19

I hope this helps. Dan

**Comment by danielweck** [comment]
This issue can be closed, right?
