### ISSUE TITLE
How to make sure a item is a valid linear item or not?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#168]
I have found this filed in a spineItem object, but it always blank
![qq 20170118172519](https://cloud.githubusercontent.com/assets/5040078/22058259/4a0cae6e-dda3-11e6-95de-1f09f190d152.png)

I also tried the method `spine.isValidLinearItem(spineItem)`, but the returns are always undefiend.

So I am confused, how can I make sure a item is a valid linear item or not?
BTW, I am building a pagination system so I need to skip no-linear items.

Thanks

**Comment by danielweck** [comment]
http://www.idpf.org/epub/301/spec/epub-publications.html#sec-itemref-elem
In EPUB's OPF `spine@itemref` element, missing `linear` attribute is synonymous with `linear="yes"`. Content creators include `linear="no"` in order to explicitly exclude a spine item from the primary reading flow.

Related Readium code:
https://github.com/readium/readium-shared-js/blob/develop/js/models/spine_item.js#L62
```javascript
    /**
     * A flag indicating whether the spineItem has the attribute linear, which 
     * is either yes or no.  Default is yes.
     *
     * @property linear
     * @type String
     * @default  yes
     */
    this.linear = itemData.linear ? itemData.linear.toLowerCase() : itemData.linear;
```

As you can see, testing for `spineItem.linear == "no" ` is sufficient to determine that a spine item is non-linear. However, `spine.isValidLinearItem(spineItemIndex)` adds an additional check for "handleLinear", which is basically a way for an application to activate / deactivate support for the "linear" property (so, make sure to invoke `spine.handleLinear(true)` before using the API).

https://github.com/readium/readium-shared-js/blob/develop/js/models/spine.js#L65
```javascript
    var _handleLinear = false;

    /**
     * Sets a flag indicating that the app handles linear spine items
     *
     * @method     handleLinear
     * @param      {Boolean} handleLinear  boolean flag
     */
    this.handleLinear = function(handleLinear) {
        _handleLinear = handleLinear;
    };

    function isValidLinearItem(item) {
        return !_handleLinear || item.linear !== "no";
    }

    /**
     * Checks if a spine item is linear. 
     *
     * @method     isValidLinearItem
     * @param      {Number} index  index of a spine item
     * @return     {Boolean} TRUE if the app does not handle linear items or if the item is linear.
    */
    this.isValidLinearItem = function(index) {
        
        if(!isValidIndex(index)) {
            return undefined;
        }

        return isValidLinearItem(this.item(index));
    };
```

**Comment by hz0324** [comment]
Thank you, sir.
