### ISSUE TITLE
Unable to play media overlay audio file

### ISSUE THREAD

**Issue by getnayan** [readium/readium-js#171]
I'm trying to play the audio file on a epub3 (fixed format with media overlay). The audio tag's src attribute is looking for a absolute path.
`<audio src="http://localhost:17105/uisvc/testlibrary/EPubContent/1234567/Content/OEBPS/audio/1234567.m4a" preload="auto"></audio>` 

It looks like when you do content fetch for resources like font, css, image and html files readium is programmatically makes them binary blobs (blob:http://localhost:17105/c210f80e-8ec7-4538-b51a-a7b5ec85c055).  

Does readium make the audio and video files as blobs ?

**Comment by danielweck** [comment]
ReadiumJS fetches resources referenced from HTML documents as binary buffers (BlobURI) only when:

1) opening a zipped EPUB container (this is why the recommended content deployment method is to unpack ebook files on the server, rather than relying on the web browser / client app to do it).

or:

2) opening a publications (zipped or not) that contains obfuscated fonts (this is why the recommended practice is to decrypt fonts on the server, rather than expect the client app to do it in the web browser).

Otherwise, if none of the above applies, than ReadiumJS *only* creates a BlobURI for the root HTML document that gets loaded in the iframe host.
