### ISSUE TITLE
getCurrentSelectionCfi() is not a function

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#176]
I find `getCurrentSelectionCfi()` in the following API doc
https://dl.dropboxusercontent.com/u/18642964/Readium/Shared-JS%20JSDoc/ReadiumSDK.Views.ReaderView.html

But when I trying to use it, browser says it is not a function. 
As you can see, its peer function is working well here.

The code is here:
![qq 20170327104630](https://cloud.githubusercontent.com/assets/5040078/24338837/dbb9fbb6-12da-11e7-9854-39cfffd641ce.png)

The console log is here:
![qq 20170327104624](https://cloud.githubusercontent.com/assets/5040078/24338847/eafc7ea0-12da-11e7-8bed-6a2f28261803.png)

Please help. Thanks.

BTW: we are trying to implement our own note/highlight system, so we need to know the selection information, especially the CFI information.

**Comment by danielweck** [comment]
Hello, I am not sure where your documentation link (DropBox) comes from, but this is not up to date.

You may generate the most up-to-date API documentation for `readium-shared-js` by invoking `npm run apidocs`:
https://github.com/readium/readium-shared-js/blob/develop/package.cson#L218

There are a number of useful CFI / DOM-Range functions in `reader_view.js`, such as `getRangeCfiFromDomRange()` which you can use to obtain CFI information from a user selection in the browser-rendered HTML document:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L1684

Obviously, rather than write your own selection/highlighting code from scratch, you may want to check Readium's existing plugin:
https://github.com/readium/readium-shared-js/tree/develop/plugins/highlights

Example usage is in `readium-js-viewer`:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L851
`readium.reader.plugins.highlights.addSelectionHighlight(Math.floor((Math.random()*1000000)), "test-highlight");`
(search for all instances of "plugins.highlights" in `EpubReader.js`)

I hope this helps.
