### ISSUE TITLE
Remove package.json from git repository

### ISSUE THREAD

**Issue by HGuillemet** [readium/readium-js#189]
#### This issue is a Other

Could you consider removing package.json and package-lock.json from git repositories (readium-js, readium-shared-js and readium-cfi-js) ?
They are causing spurious non-meaningful commits after you update modules, and block pulls when our local package.json differs from the one in the repository.
package.cson should be the only file versioned IMO.

Thanks,

**Comment by danielweck** [comment]
Hello, thank you for your feedback / suggestions.
* 'package-lock.json' is the authoritative representation of a working build (frozen versions of external dependencies) at any given time (git revision) in the codebase. It should definitely remain in the source tree.
* 'package.json' absolutely needs to remain in the source tree as it is required to setup the project in the first place, and to iterate development. However, it is currently automatically generated from a friendlier CSON syntax (which allows comments and line breaks), and unfortunately the alphabetical sorting of "dependencies" JSON properties is affected each time 'npm install or update' modify the file (thereby ignoring the CSON source entirely). This problem is solved in other Readium "2" projects by using CSON only for the scripts section of 'package.json', and it would be good to backport this technique in Readium "1" to avoid the out-of-synx problems.
* lastly, it is normal that 'npm update' bumps-up version numbers in 'package.json' (as well as the lock file) whenever appropriate. But, NPM 'update' should be seen as the equivalent to changing code in Readium's own source tree, with a degree of risk in terms of regression bugs etc. This is why only 'npm install' should be used to setup the project, as this will populate node_modules with packages that conform strictly to the versions specified in the lock file.

Note that recent NPM CLI updates have drastically improved the lockfile and node_modules handling, notably with the introduction of 'npm ci' (instead of 'npm install' for deployments / release builds), but also other fixes in 'npm udpate'.

**Comment by danielweck** [comment]
PS
take note of the 'prepare:local' task which tries 'npm ci' and falls-back to 'npm install':
https://github.com/readium/readium-js/blob/develop/package.cson
Also note that 'npm update' is not involved in this project preparation stage.

Additionally in Readium "2" NPM projects, the 'ncu' utility is used to ensure that "caret" semantic versions in 'package.json' are in sync with the latest versions expressed in the NPM lockfile. This makes the project definition more human-friendly / readable in terms of its external dependencies.

**Comment by HGuillemet** [comment]
Thanks for this detailed answer. Closing the issue.
